[package]
name = "producer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
dashmap = "5.4.0"
log = "0.4.17"
once_cell = "1.17.1"
rdkafka = { version = "0.29.0", features = ["cmake-build"] }
robusta_jni = "0.2.1"
simple_logger = "4.1.0"
